image:
  tag: 1.4.0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
  path: /
  hosts:
    # TODO: Change this back
    - www.getsafefood.com 
  tls:
    - secretName: ca--tls
      hosts:
        # TODO: Change this back
        - www.getsafefood.com 

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

caName: ca

postgresql:
  enabled: true

config:
  hlfToolsVersion: 1.4.0
  csr:
    names:
      c: US 
      st: California 
      l:
      o: "iTradeNetwork"
      ou: Blockchain
  affiliations:
    iTradeNetwork: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-ca
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: postgresql
          release: ca
      topologyKey: "kubernetes.io/hostname"
